README.md
common-compose.yml
makefile

@misterbisson this updates the repo to have container images moved under the autopilotpattern org.
The new images have been pushed to:
https://hub.docker.com/r/autopilotpattern/mysql/

Move images to autopilotpattern repo

---

bin/triton-mysql.py

For https://github.com/autopilotpattern/mysql/issues/17
Because we set the "binlog isn't stale" flag at the end of a backup, a newly started cluster will spawn many `create_snapshot` processes even though we're locking the BACKUP_TTL in Consul. This adds a local file lock that prevents the node from running multiples.
Also removed an unnecessary reliance on the repl user having access to the end-user's data DB just to run health checks.
cc @misterbisson @moretea  I need to do a bit more testing on this but I think it's the right approach.

Add a file lock around creation of a snapshot

---

bin/manage.py

There is a race between the onChange and health handler around stopping replication while we figure out which instance is primary. These leaves the onChange handler in an infinite loop because we previously assumed that the only errors we'd get were from the session lock.
This PR breaks the loop when error code 1198 ER_SLAVE_MUST_STOP is received from mysqld, which says that replication has already been started.
cc @misterbisson for review

Stop replication

---

etc/my.cnf.tmpl

The manage.py script calculates this value in Megabytes, so the
template should indicate this.  The default unit is Bytes.
Edit by @misterbisson: fixes https://github.com/autopilotpattern/mysql/issues/32

Change the $buffer substitution to include the unit (Megabyte).

---

Dockerfile

Those packages are needed to build the `cffi` and `cryptography` wheels.
Without them, the following errors are thrown:
```
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
#include <ffi.h>
^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
----------------------------------------
Failed building wheel for cffi
```
and ...
```
build/temp.linux-x86_64-2.7/_openssl.c:423:30: fatal error: openssl/opensslv.h: No such file or directory
#include <openssl/opensslv.h>
^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
----------------------------------------
Failed building wheel for cryptography
```

Add missing packages

---

README.md
bin/manage.py

Defaults to the previous value that includes a timestamp, but allows the user to override it.
This is useful so that while developing locally there’s only one backup in Manta, e.g. `BACKUP_NAME=my-dev-mysql-backup` as opposed to multiple ones.

Allow custom `BACKUP_NAME` with `strftime` support.

---

README.md
bin/manage.py

This allows us to, for example, use env vars from the host machine where `docker-compose` runs.

Enable environment variables expansion.

---

docker-compose.yml
local-compose.yml
makefile
shippable.yml
tests/Dockerfile
tests/tests.py

@misterbisson this is the work-in-progress PR.

Test on shippable

---

Dockerfile
bin/manage.py
bin/test.py
docker-compose.yml
etc/containerpilot.json
local-compose.yml
setup.sh

For https://github.com/autopilotpattern/mysql/issues/43 (and https://github.com/autopilotpattern/mysql/issues/18)
Start a ContainerPilot coprocess for the Consul agent when CONSUL_AGENT is set. This Consul agent joins the raft found at the CONSUL env var. The `manage.py` application sends most Consul requests to this agent whenever it's available. During `preStart` we query the Consul raft because the co-process agent isn't running yet.
Includes:
- Updated containerpilot.json and Compose .yml files to include env variables for CONSUL_AGENT.
- Added unit test for handling the containerpilot.json template when we rewrite the ContainerPilot config after an instance becomes the primary.
- Moved a lot of the Dockerfile into a single RUN so that we can clean ourselves up without leaving extra …

Run Consul agent as co-process.

---

bin/manage.py
etc/containerpilot.json

For https://github.com/autopilotpattern/mysql/issues/44
Move snapshots out of the health check and into a periodic task. This allows us to avoid causing the health check on the primary from failing if the snapshot takes longer than the heartbeat TTL we sent to Consul.
Although the Shippable test rig is still intermittently failing regardless, I managed to get a working test run out of this:
```
----------------------------------------------------------------------
MySQLStackTest.test_replication_and_failover
----------------------------------------------------------------------
elapsed  | task
1.311280 | docker-compose -f local-compose.yml -p my up -d
0.265898 | docker-compose -f local-compose.yml -p my ps
0.028845 | docker inspect my_consul_1
27.19103 | wait_for_service: mysql-primary 1 …
```

Move snapshot from health check to task

---

Dockerfile
bin/manage.py
docker-compose.yml
etc/containerpilot.json
local-compose.yml
makefile
shippable.yml
tests/Dockerfile
tests/tests.py

For https://github.com/autopilotpattern/mysql/issues/30
Includes:
- Bump ContainerPilot to 2.4.1
- Split tagging from shipping so you can do local testing w/ `make build tag test-local-docker` w/o shipping to the Docker Hub
- Make ContainerPilot log level respect the same `LOG_LEVEL` env var that the `manage.py` script does
- Make unit testing work on Shippable
- Clean up some logging and exception handling quirks

Logging and exception handling improvements

---

makefile

@misterbisson this should fix the unit test runs on Shippable. (ref [build](https://app.shippable.com/runs/57c48e94c96a570f00b9e228))

Remove tty flag from unit-test run, for compat w/ Shippable

---

Dockerfile

This fixes a problem discovered during investigation of #59. 
The golang stdlib (and our `RunAndWait` implementation in ContainerPilot) has a race where if we call `Wait` after the child process has already exited and been cleaned up then an error bubbles up through the stack. This breaks the heartbeat TTL and causes the primary to be marked as unhealthy prematurely. This will aggravate the problem described in #59 (although this fix won't correct it entirely).
cc @misterbisson @jasonpincin

Update ContainerPilot to 2.4.2

---

README.md
bin/manage.py
bin/manager/libconsul.py
bin/manager/libmysql.py
bin/manager/utils.py
bin/test.py

For https://github.com/autopilotpattern/mysql/issues/59
When we registered a check for the snapshot, it was not being bound to a particular service and so when it failed the check the entire node was being marked as unhealthy. Instead of further overloading the Consul services concept, we'll just write a key with the last snapshot's timestamp to Consul and then compare the timestamps against the current time and the `BACKUP_TTL` value.
cc @misterbisson @jasonpincin for review and discussion

Record timestamp for last snapshot rather than overloading service

---

Dockerfile
docker-compose.yml

For https://github.com/autopilotpattern/mysql/issues/56
This permits us to use the by-default `leave_on_terminate` option in 0.7.0 in our Consul agent.

Upgrade Consul to 0.7

---

makefile
setup.sh
shippable.yml
tests/tests.py

Updates the test running so that we don't tear down all our containers on a failed test run so that we can do post-mortem debugging (except on Shippable where we can't debug them anyways).
Depends on https://github.com/autopilotpattern/testing/pull/11
cc @jasonpincin @misterbisson

Take advantage of failfast from autopilotpattern/testing

---

tests/tests.py

Integration tests were "randomly" failing whenever the UUID of the value we wrote to MySQL started with the "d", "e", or "f" characters because these were getting stripped off during parsing and we'd incorrectly report this as a replication failure.
cc @jasonpincin @misterbisson

Fix parsing of MySQL row in test rig to avoid intermittent test failures

---

Dockerfile

This PR upgrades ContainerPilot to 2.6.0, which will move us past the health check bug fixed in 2.4.3, and upgrades Consul to 0.7.1 just to keep current with their patch set (and #73)
cc @misterbisson @jasonpincin

Upgrade ContainerPilot to 2.6.0, Consul to 0.7.1

---

bin/manager/containerpilot.py
docker-compose.yml

This PR is for problems discovered with Consul clustering as part of debugging https://github.com/autopilotpattern/mysql/issues/71.
The Consul server was continually trying to join itself because I switched it to use autopilotpattern/consul when it's only a single-node cluster.
Also, when we reload the config for the primary, the logic in manager/containerpilot.py includes the port 8500 in the `-retry-join` field which [it should not](https://github.com/hashicorp/consul/issues/1643). So we join Consul just fine and then keep trying to re-join on a port that doesn't work after the reload.
cc @misterbisson @jasonpincin @mbbender

Fix Consul --retry-join failure

---

bin/manage.py
bin/manager/libconsul.py

@tgross,
This should fix the replication issue of #71 and autopilotpattern/wordpress#42.
So far it has worked for me, but I haven't been able to run tests in my on-prem triton.
Until the PR is merged, I will keep the docker image in sync here [zeroae/mysql:i-71-replication](https://hub.docker.com/r/zeroae/mysql/tags/).

[WIP] Correct state machine for is_primary, is_replica, UNASSIGNED.

---

README.md
bin/manager/containerpilot.py
bin/manager/utils.py
docker-compose.yml
etc/containerpilot.json

Per the discussion in https://github.com/joyent/containerpilot/issues/260 and @tgross request at https://github.com/joyent/containerpilot/issues/260#issuecomment-270137432
Still defaults to a service name of `"mysql"`, but can be overridden by the env var `SERVICE_NAME`.
This allows one to use the exact same image in the same environment for different services, e.g. having three mysql instances for `authdb`, 2 more for `ordersdb`, etc.

Add support for defining service name in env var

---

Dockerfile
bin/manage.py
bin/manager/storage/minio_stor.py
examples/compose/docker-compose.yml

Adds support for an S3 snapshotter via Minio. Replaces local storage in the compose example as a solution for https://github.com/autopilotpattern/mysql/issues/35.
There was also the question of whether or not we should change the name from `Minio` to S3, since it's really an S3 interface, and Minio just happens to be the preferred implementation. @tianon figured that @misterbisson or @tgross should make the call on that.

Minio Snapshotter
